services:
  image_uploader:
    image: notfullmetal/spotifynow:latest
    command: python3 spotifynow.py
    restart: on-failure
    volumes:
      - ./config.json:/app/config.json
      - ./spotifynow.db:/app/spotifynow.db