name: SpotifyNow
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GH_IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERPW }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
  

      - name: Build & Push image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
          -t notfullmetal/spotifynow:${{ env.SHORT_SHA }} \
          -t notfullmetal/spotifynow:${{ github.ref_name }} \
          -t notfullmetal/spotifynow:latest \
          -t $GH_IMAGE_REPOSITORY:${{ env.SHORT_SHA }} \
          -t $GH_IMAGE_REPOSITORY:${{ github.ref_name }} \
          -t $GH_IMAGE_REPOSITORY:latest \
          . --push